version: '3.3'

services:

    privatebin:
        image: privatebin/nginx-fpm-alpine
        container_name: privatebin
        restart: unless-stopped
        read_only: true  #false    
        ports:
            - "8200:8080"
        volumes:
            - ./privatebin-data:/srv/data

